language: php

php: 5.4

before_install:
  - composer self-update

install:
  - composer self-update
  - composer install --no-dev --prefer-dist --optimize-autoloader

script:
  - ls

deploy:
  provider: releases
  api_key:
    secure: DT6qfSlb6dVuXZKMnPLddyheWDsAargfBD2KfchL3uIy86c7iJBeovXXZxdXQDslDAMfllJqCsTeuX0arfUXLJYwT54aNysBqdrnz9TZcsovcM3E+g8YCWjIrbVMG46wXC2cz8DMrhXhHlg36BzNrEaWIe+ov5gp6EgafWyhK2U=
  file: libs/global/
  skip_cleanup: true
  on:
    repo: skaut/SRS
    branch: travis
    tags: true
